apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-config
data:
  jvm.options: |
    -Dapplication.rest.client.CloudantClientService/mp-rest/url=http://{{ .Values.couchdb.host }}:{{ .Values.couchdb.port }}
