apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-{{ .Values.service.name }}-populate"
spec:
  template:
    # Used with istio
    # metadata:
    #   annotations:
    #     sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: populate
        image: populate
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "python3 /tmp/populate.py  {{ .Release.Name }}-{{ .Values.couchdb.hostSuffix }} {{ .Values.couchdb.service.externalPort }}"]
      restartPolicy: Never
