apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-populate"
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: populate
        image: populate
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "python3 /tmp/populate.py  {{ .Values.couchdb.host }} {{ .Values.couchdb.port }}"]
      restartPolicy: Never
