apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Values.service.name }}"
  labels:
    chart: "{{ .Release.Name }}-{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    implementation: microprofile
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.servicePort }}
  - name: https
    port: {{ .Values.service.servicePortHttps }}
  selector:
    app: bluecompute
    micro: customer
    service: server
    release: {{ .Release.Name }}
    implementation: microprofile
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-{{ .Values.service.name }}"
  labels:
    app: bluecompute
    micro: customer
    service: server
    tier: backend
    release: {{ .Release.Name }}
    implementation: microprofile
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: bluecompute
        micro: customer
        service: server
        tier: backend
        release: {{ .Release.Name }}
        implementation: microprofile

    spec:
      containers:
      # Liberty Server Container
      - name: "{{ .Chart.Name }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        #image: customer
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /
            port: 9443
            scheme: HTTPS
          initialDelaySeconds: 60
          timeoutSeconds: 60
        livenessProbe:
          httpGet:
            path: /health
            port: 9443
            scheme: HTTPS
          initialDelaySeconds: 1500
          timeoutSeconds: 500
        env:
          {{ if .Values.travis }} 
          - name: jwksUri
            value: "https://{{ .Values.service.minikubeIp }}:{{ .Values.service.authKubePort }}/oidc/endpoint/OP/jwk"
          - name: jwksIssuer
            value: "https://{{ .Values.service.minikubeIp }}:9443/oidc/endpoint/OP"
          - name: administratorRealm
            value: "user:https://{{ .Values.service.minikubeIp }}:9443/oidc/endpoint/OP/user"
          - name: auth_health
            value: "https://{{ .Values.service.minikubeIp }}:{{ .Values.service.authKubePort }}/health"
        {{ else }}
          - name: jwksUri
            value: "https://{{ .Release.Name }}-{{ .Values.service.auth }}:9443/oidc/endpoint/OP/jwk"
          - name: jwksIssuer
            value: "https://{{ .Release.Name }}-{{ .Values.service.auth }}:9443/oidc/endpoint/OP"
          - name: administratorRealm
            value: "user:https://{{ .Release.Name }}-{{ .Values.service.auth }}:9443/oidc/endpoint/OP/user"
          - name: auth_health
            value: "https://{{ .Release.Name }}-{{ .Values.service.auth }}:9443/health"
        {{ end }}
          - name: host
            value: "{{ .Release.Name }}-{{ .Values.service.cloudantservicename }}"
          - name: PORT
            value: "{{ .Values.service.servicePort }}"
          - name: RELEASE_NAME
            value: "{{ .Release.Name }}"
          - name: jwtid
            value: "{{ .Values.jwt.id }}"
          - name: zipkinHost
            value: "{{ .Release.Name }}-{{ .Values.service.zipkinHost }}"
          - name: zipkinPort
            value: "{{ .Values.service.zipkinPort }}"
        resources:
          requests:
            cpu: "{{ .Values.image.resources.requests.cpu }}"
            memory: "{{ .Values.image.resources.requests.memory }}"
        volumeMounts:
        - name: keystorevol
          mountPath: "/etc/keystorevol"
          readOnly: true
        - name: config-volume
          mountPath: {{ .Values.volumes.mountPath }}
      volumes:
      - name: keystorevol
        secret:
          secretName: keystoresecret
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}-{{ .Chart.Name }}-config
