apiVersion: v1
entries:
  customer:
  - apiVersion: v1
    created: "2019-11-20T14:48:41.003584-06:00"
    description: A Helm chart for Kubernetes
    digest: aa205cb99cd8d8bc262e84b83baea0199be4f9fd2d195b29a946b85577a2661a
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: customer
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-customer/tree/microprofile
    urls:
    - customer-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v1
    created: "2019-11-20T14:48:41.002835-06:00"
    description: A Helm chart for Kubernetes
    digest: adf21351b6687962856df80aaa71d2cc792b9fb82946091756cab9ed88e317eb
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: customer
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-customer/tree/microprofile
    urls:
    - customer-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v1
    created: "2019-11-20T14:48:41.001466-06:00"
    description: A Helm chart for Kubernetes
    digest: 5624b6ec9885c712fb91e0ba58eac9b2c54f096df2caa62e1c2eaffc0c5c2e8d
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: customer
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-customer/tree/microprofile
    urls:
    - customer-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v1
    created: "2019-11-20T14:48:40.999806-06:00"
    description: A Helm chart for Kubernetes
    digest: 81307176e4559a2d2cb2187c2669472681375dde27aeb0071faa93122a21528c
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: customer
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-customer/tree/microprofile
    urls:
    - customer-0.0.1.tgz
    version: 0.0.1
generated: "2019-11-20T14:48:40.998783-06:00"
