apiVersion: v1
entries:
  customer:
  - apiVersion: v1
    created: "2019-12-16T12:08:09.890347-06:00"
    description: A Helm chart for Kubernetes
    digest: cf9186dbdfedd056f5487fbfea3a0b5dfd6826f066e961911f68e2b38b09c142
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: customer
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-customer/tree/microprofile
    urls:
    - customer-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v1
    created: "2019-12-16T12:08:09.884416-06:00"
    description: A Helm chart for Kubernetes
    digest: adf21351b6687962856df80aaa71d2cc792b9fb82946091756cab9ed88e317eb
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: customer
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-customer/tree/microprofile
    urls:
    - customer-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v1
    created: "2019-12-16T12:08:09.882904-06:00"
    description: A Helm chart for Kubernetes
    digest: 5624b6ec9885c712fb91e0ba58eac9b2c54f096df2caa62e1c2eaffc0c5c2e8d
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: customer
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-customer/tree/microprofile
    urls:
    - customer-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v1
    created: "2019-12-16T12:08:09.881707-06:00"
    description: A Helm chart for Kubernetes
    digest: 81307176e4559a2d2cb2187c2669472681375dde27aeb0071faa93122a21528c
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: customer
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-customer/tree/microprofile
    urls:
    - customer-0.0.1.tgz
    version: 0.0.1
generated: "2019-12-16T12:08:09.879765-06:00"
